name: Manual Generate APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

    inputs:

      baseUrl:
        description: 'Base URL'
        required: true
        default: 'https://production.example.com/api/v1'

      apiKey:
        description: 'Api Key'
        required: true
        default: 'BE url'

      gateway:
        description: 'Gateway'
        required: true
        default: 'v1'

      appType:
        description: 'Apptype'
        required: true
        default: 'android'


#      reAttempt:
#        description: 'Number of re-attempts'
#        default: '3'
#
#      thresholdValue:
#        description: 'Threshold value'
#        default: '0.05'

jobs:

  apk:
    name: Generate Debug APK
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Print Params Values
        run: |
          bash update_properties.sh ${{ github.event.inputs.baseUrl }} ${{ github.event.inputs.apiKey }} ${{ github.event.inputs.gateway }} ${{ github.event.inputs.appType }}
      - name: Assemble app debug APK
        run: bash ./gradlew assembleDebug --stacktrace

      - name: Upload app APK
        uses: actions/upload-artifact@v1
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk